export const VerdictEnum = {
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  FLAGGED_FOR_REVIEW: 'FLAGGED_FOR_REVIEW'
};

export const EngineTierEnum = {
  TIER_1_DETERMINISTIC: 'TIER_1_DETERMINISTIC',
  TIER_2_SEMANTIC_AI: 'TIER_2_SEMANTIC_AI',
  HYBRID_FUSION: 'HYBRID_FUSION'
};

export const ViolationCategoryEnum = {
  PROFANITY: 'PROFANITY',
  HATE_SPEECH: 'HATE_SPEECH',
  TOXICITY: 'TOXICITY',
  SPAM: 'SPAM',
  PII_LEAK: 'PII_LEAK',
  SUSPICIOUS_LINK: 'SUSPICIOUS_LINK',
  IMPLICIT_THREAT: 'IMPLICIT_THREAT'
};

export const EntityTypeEnum = {
  COMMENT: 'comment',
  POST: 'post',
  CHAT_MESSAGE: 'chat_message',
  USER_BIO: 'user_bio'
};
